
# define the virtual network both containers will connect to
networks:
  chat_network:
    driver: bridge

services:
  # --- container 1: server ---
  server:
    build: .                    # build using our Dockerfile
    image: secure_chat          # name the image
    container_name: chat_server
    networks:
      - chat_network
    command: ["./build/output/main", "server", "9000"]
    stdin_open: true            # keep stdin open so we can type
    tty: true                   # allocate a terminal

  # --- container 2: client ---
  client:
    build: .
    image: secure_chat
    container_name: chat_client
    networks:
      - chat_network
    command: ["./build/output/main", "client", "chat_server", "9000"]
    stdin_open: true
    tty: true
    depends_on:
      - server                  # wait for server container to start first
